repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.0
    hooks:
      - id: seed-isort-config
        language_version: python3.7
        args: [--application-directories=src]
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
      - id: isort
        language_version: python3.7
        types: [python]
        exclude: (/migrations/)
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
        types: [python]
        exclude: (/migrations/)
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear==20.1.4]
        language_version: python3.7
        types: [python]
        exclude: (/migrations/|manage.py)
