default_language_version:
  python: python3
exclude: (^docs/|/migrations/|manage.py)
repos:
  - repo: https://github.com/base-angewandte/pre-commit-hooks
    rev: py3.8
    hooks:
      - id: base-hooks
