version: '2.3'
services:

  showroom-redis:
    image: redis:6.0-alpine
    container_name: showroom-redis
    volumes:
      - ./dockerdata/redis/data:/data
    networks:
      - showroomnet
    restart: always
    command: redis-server --appendonly yes

  showroom-postgres:
    image: postgres:13-alpine
    container_name: showroom-postgres
    environment:
      - POSTGRES_PASSWORD=$SHOWROOM_DB_PASSWORD
      - POSTGRES_USER=$SHOWROOM_DB_USER
      - POSTGRES_DB=$SHOWROOM_DB_NAME
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./dockerdata/postgres/13/data:/var/lib/postgresql/data/pgdata
    networks:
      - showroomnet
    restart: always

  showroom-django:
    build: ./src
    container_name: showroom-django
    environment:
      - POSTGRES_PASSWORD=$SHOWROOM_DB_PASSWORD
      - POSTGRES_USER=$SHOWROOM_DB_USER
      - POSTGRES_DB=$SHOWROOM_DB_NAME
    expose:
      - 8500
    volumes:
      - ./src:/django
      - ./logs:/logs
      - $SHOWROOM_ASSETS:/django/assets
    networks:
      - showroomnet
    restart: always

  showroom-rq-worker-1:
    build: ./src
    container_name: showroom-rq-worker-1
    environment:
      - POSTGRES_PASSWORD=$SHOWROOM_DB_PASSWORD
      - POSTGRES_USER=$SHOWROOM_DB_USER
      - POSTGRES_DB=$SHOWROOM_DB_NAME
    volumes_from:
      - showroom-django
    networks:
      - showroomnet
    restart: always
    command: python manage.py rqworker --with-scheduler default

  showroom-rq-worker-2:
    build: ./src
    container_name: showroom-rq-worker-2
    environment:
      - POSTGRES_PASSWORD=$SHOWROOM_DB_PASSWORD
      - POSTGRES_USER=$SHOWROOM_DB_USER
      - POSTGRES_DB=$SHOWROOM_DB_NAME
    volumes_from:
      - showroom-django
    networks:
      - showroomnet
    restart: always
    command: python manage.py rqworker --with-scheduler high default

  showroom-cron:
    image: paradoxon/alpine-cron
    container_name: showroom-cron
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/cron/crontab:/tmp/crontab
    network_mode: "none"
    restart: always


networks:
  showroomnet:
