# Generated by Django 3.2.13 on 2022-07-12 13:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pluginapikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pluginapikey',
            options={'verbose_name': 'Plugin API key', 'verbose_name_plural': 'Plugin API keys'},
        ),
        migrations.AlterField(
            model_name='pluginapikey',
            name='allowed_ips',
            field=models.JSONField(default=api.models.get_default_allowed_ips, help_text='JSON list of IPs that are allowed to use this key. Use * for any.', validators=[api.models.validate_ips]),
        ),
        migrations.AlterField(
            model_name='pluginapikey',
            name='note',
            field=models.TextField(blank=True, help_text='Optional internal note for admins.'),
        ),
        migrations.AlterField(
            model_name='pluginapikey',
            name='plugins',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of plugins that can be used with this key. Available plugins: repo_source', validators=[api.models.validate_plugins]),
        ),
    ]
