# Generated by Django 2.2.16 on 2021-04-01 10:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import general.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceRepository',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('label_institution', models.CharField(max_length=255)),
                ('label_repository', models.CharField(max_length=255)),
                ('url_institution', models.CharField(max_length=255)),
                ('url_repository', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('api_key', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('id', general.models.ShortUUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('list', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('primary_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('secondary_detials', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('locations', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('dates', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('source_repo_entry_id', models.CharField(max_length=255)),
                ('type', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', general.models.ShortUUIDField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('i', 'Image'), ('a', 'Audio'), ('v', 'Video'), ('d', 'Document'), ('x', 'Undefined')], max_length=1)),
                ('file', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('exif', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('license', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('id', general.models.ShortUUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('list', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('primary_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('secondary_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('locations', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('dates', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('source_repo_entry_id', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('P', 'person'), ('I', 'institution'), ('D', 'department')], max_length=1)),
                ('expertise', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('showcase', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(blank=True, limit_choices_to=models.Q(('type', 'I'), ('type', 'D'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Entity')),
                ('source_repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.SourceRepository')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', general.models.ShortUUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('secondary_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('activities', models.ManyToManyField(to='core.Activity')),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Entity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='featured_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_by', to='core.Media'),
        ),
        migrations.AddField(
            model_name='activity',
            name='source_repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.SourceRepository'),
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='secondary_detials',
            new_name='secondary_details',
        ),
        migrations.AddField(
            model_name='activity',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='core.Activity'),
        ),
    ]
