# Generated by Django 3.2.12 on 2022-04-05 12:19

import core.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydetail',
            name='activity_type',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitydetail',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entitydetail',
            name='expertise',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entitydetail',
            name='list',
            field=models.JSONField(default=dict, validators=[core.validators.validate_entity_list]),
        ),
        migrations.AlterField(
            model_name='entitydetail',
            name='list_ordering',
            field=models.JSONField(default=core.models.get_default_list_ordering, validators=[core.validators.validate_list_ordering]),
        ),
        migrations.AlterField(
            model_name='entitydetail',
            name='showcase',
            field=models.JSONField(blank=True, null=True, validators=[core.validators.validate_showcase]),
        ),
        migrations.AlterField(
            model_name='media',
            name='exif',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='license',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='specifics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showroomobject',
            name='list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showroomobject',
            name='locations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showroomobject',
            name='primary_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showroomobject',
            name='secondary_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showroomobject',
            name='source_repo_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='showroomobject',
            name='subtext',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
