# Generated by Django 2.2.27 on 2022-04-04 18:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroomobject',
            name='source_repo_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
