# Generated by Django 2.2.16 on 2021-05-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210512_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='dates',
        ),
    ]
