# Generated by Django 3.2.12 on 2022-04-06 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220405_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateRelevanceIndex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('showroom_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.showroomobject')),
            ],
        ),
    ]
