# Generated by Django 3.2.12 on 2022-04-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_daterelevanceindex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['order', '-created']},
        ),
        migrations.AddField(
            model_name='media',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='media',
            name='order',
            field=models.PositiveIntegerField(default=2147483647),
        ),
    ]
