# Generated by Django 2.2.16 on 2021-06-09 13:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210526_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
