# Generated by Django 2.2.16 on 2021-06-09 13:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='subtext',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='subtext',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
