# Generated by Django 3.2.13 on 2022-04-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220407_1137'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sourcerepository',
            index=models.Index(fields=['api_key'], name='core_source_api_key_08b0c3_idx'),
        ),
    ]
