# Generated by Django 3.2.13 on 2022-10-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shorten_entity_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='daterelevanceindex',
            name='rank',
            field=models.IntegerField(default=2147483647),
        ),
    ]
