# Generated by Django 2.2.16 on 2021-06-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210609_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='source_repo_owner_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
