# Generated by Django 3.2.13 on 2022-04-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sourcerepository_core_source_api_key_08b0c3_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroomobject',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
