# Generated by Django 2.2.16 on 2021-06-09 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activity_source_repo_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Entity'),
        ),
    ]
