# Generated by Django 3.2.13 on 2022-04-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_showroomobject_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitydetail',
            name='photo',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
