# Generated by Django 2.2.16 on 2021-07-06 09:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210609_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='specifics',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
