# Generated by Django 2.2.16 on 2021-07-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_media_specifics'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='source_repo_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
