# Generated by Django 3.2.13 on 2022-04-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_entitydetail_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showroomobject',
            options={},
        ),
        migrations.AddIndex(
            model_name='showroomobject',
            index=models.Index(fields=['source_repo_object_id'], name='core_showro_source__d220b7_idx'),
        ),
    ]
