# Generated by Django 2.2.16 on 2021-07-08 12:10

from django.db import migrations, models
import django.db.models.deletion
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_media_source_repo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='parents',
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', general.models.ShortUUIDField(primary_key=True, serialize=False)),
                ('from_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_entries', to='core.Activity')),
                ('to_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_entries', to='core.Activity')),
            ],
            options={
                'unique_together': {('from_entry', 'to_entry')},
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='relations',
            field=models.ManyToManyField(related_name='related_to', through='core.Relation', to='core.Activity'),
        ),
    ]
