# Generated by Django 3.2.13 on 2022-04-24 23:42

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_showroomobject_unique_together'),
    ]

    operations = [
        BtreeGinExtension(),
        TrigramExtension(),
        migrations.AddIndex(
            model_name='showroomobject',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='core_showro_title_491ff7_gin'),
        ),
        migrations.AddIndex(
            model_name='textsearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text'], name='core_textse_text_97f15d_gin'),
        ),
    ]
