# Generated by Django 2.2.16 on 2021-07-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210708_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='relations',
        ),
        migrations.AddField(
            model_name='activity',
            name='relations_to',
            field=models.ManyToManyField(blank=True, related_name='relations_from', to='core.Activity'),
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
