# Generated by Django 3.2.13 on 2022-04-28 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220425_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_set', to='core.showroomobject')),
                ('to_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_set', to='core.showroomobject')),
            ],
        ),
        migrations.RemoveField(
            model_name='showroomobject',
            name='relations_to',
        ),
        migrations.AddField(
            model_name='showroomobject',
            name='relations_to',
            field=models.ManyToManyField(blank=True, related_name='relations_from', through='core.Relation', to='core.ShowroomObject'),
        ),
        migrations.AddIndex(
            model_name='relation',
            index=models.Index(fields=['from_object'], name='core_relati_from_ob_b8a972_idx'),
        ),
        migrations.AddIndex(
            model_name='relation',
            index=models.Index(fields=['to_object'], name='core_relati_to_obje_f9da9b_idx'),
        ),
    ]
