# Generated by Django 2.2.16 on 2021-07-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210713_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='source_repo_id',
            new_name='source_repo_media_id',
        ),
    ]
