# Generated by Django 3.2.13 on 2022-04-28 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220428_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorActivityRelations',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contributor_source_id', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_usernames', to='core.showroomobject')),
            ],
        ),
        migrations.AddIndex(
            model_name='contributoractivityrelations',
            index=models.Index(fields=['contributor_source_id'], name='core_contri_contrib_2c289e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contributoractivityrelations',
            unique_together={('contributor_source_id', 'activity')},
        ),
    ]
