# Generated by Django 3.2.13 on 2022-04-29 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220428_1332'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('from_object', 'to_object')},
        ),
    ]
