# Generated by Django 2.2.16 on 2021-07-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_activity_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='source_repo_data_text',
            field=models.TextField(default=''),
        ),
    ]
