# Generated by Django 2.2.16 on 2021-11-22 14:53

import core.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_activity_search_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='showcase',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[core.validators.validate_showcase]),
        ),
        migrations.CreateModel(
            name='ActivitySearchDates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySearchDateRanges',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Activity')),
            ],
        ),
    ]
