# Generated by Django 2.2.11 on 2021-12-02 15:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20211122_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='source_user_preferences_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
