# Generated by Django 2.2.11 on 2021-12-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_entity_source_user_preferences_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='source_user_preferences_data',
            new_name='source_repo_data',
        ),
    ]
