# Generated by Django 2.2.16 on 2022-02-01 14:12

import core.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20211213_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='source_repo_data_text',
        ),
        migrations.AddField(
            model_name='activity',
            name='collection_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='list_ordering',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=core.models.get_default_list_ordering),
        ),
    ]
