# Generated by Django 2.2.16 on 2022-02-02 10:26

import core.models
import core.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20220201_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='list',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, validators=[core.validators.validate_entity_list]),
        ),
        migrations.AlterField(
            model_name='entity',
            name='list_ordering',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=core.models.get_default_list_ordering, validators=[core.validators.validate_list_ordering]),
        ),
    ]
