# Generated by Django 2.2.27 on 2022-03-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20220202_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date_synced',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='date_synced',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
