FROM python:3.8

ENV PYTHONUNBUFFERED 1

RUN mkdir /logs
VOLUME /logs

WORKDIR /django
COPY requirements-dev.txt .
RUN pip install  --no-cache-dir --upgrade pip==20.2.3 \
  && pip install --no-cache-dir pip-tools==5.3.1 \
  && pip-sync requirements-dev.txt
